export const SERVANT_CHANGE = 'SERVANT_CHANGE'
export const SERVANT_RANK_CHANGE = 'SERVANT_RANK_CHANGE'
export const SERVANT_AVATARS_FETCHED = 'SERVANT_AVATARS_FETCHED'
export const SERVANT_AVATAR_CHANGED = 'SERVANT_AVATAR_CHANGED'
