export const SERVANTS_LOAD = 'SERVANTS_LOAD'
export const SERVANTS_ADD = 'SERVANTS_ADD'
export const SERVANTS_REMOVE = 'SERVANTS_REMOVE'
export const SERVANTS_UPDATE = 'SERVANTS_UPDATE'

export const SERVANTS_CHANGE = 'SERVANTS_CHANGE'
